apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
  namespace: microservices
  labels:
    app: order-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
        - name: order-processing
          image: order-processing-service:latest
          imagePullPolicy: Never  # Usa imagem local do Minikube
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: order-processing-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
