apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: orders.microservices.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-processing-service
                port:
                  number: 80
    - host: notifications.microservices.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-notification-service
                port:
                  number: 80
