apiVersion: v1
kind: Service
metadata:
  name: order-notification-service
  namespace: microservices
spec:
  selector:
    app: order-notification
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
